# Generated by Django 6.0.7 on 2026-08-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_branch_student_city_student_college_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='interests',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
