# Generated by Django 6.0.7 on 2026-08-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_interests_student_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='experience_level',
            field=models.CharField(default='Beginner', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='target_job',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
